/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GameplayLogicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAO_SHARE_BP"
      | "addRecipe"
      | "craft"
      | "daoTreasury"
      | "devWallet"
      | "graceToken"
      | "holyRelics"
      | "owner"
      | "recipeCount"
      | "recipes"
      | "renounceOwnership"
      | "sacredItems"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Crafted"
      | "FundsDistributed"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAO_SHARE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRecipe",
    values: [
      BigNumberish[],
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "craft", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "daoTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "devWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "graceToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "holyRelics",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recipeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sacredItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DAO_SHARE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRecipe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "craft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "graceToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "holyRelics", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recipeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recipes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sacredItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CraftedEvent {
  export type InputTuple = [
    player: AddressLike,
    recipeId: BigNumberish,
    resultTokenId: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    player: string,
    recipeId: bigint,
    resultTokenId: bigint,
    success: boolean
  ];
  export interface OutputObject {
    player: string;
    recipeId: bigint;
    resultTokenId: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDistributedEvent {
  export type InputTuple = [
    total: BigNumberish,
    daoAmount: BigNumberish,
    devAmount: BigNumberish
  ];
  export type OutputTuple = [
    total: bigint,
    daoAmount: bigint,
    devAmount: bigint
  ];
  export interface OutputObject {
    total: bigint;
    daoAmount: bigint;
    devAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameplayLogic extends BaseContract {
  connect(runner?: ContractRunner | null): GameplayLogic;
  waitForDeployment(): Promise<this>;

  interface: GameplayLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAO_SHARE_BP: TypedContractMethod<[], [bigint], "view">;

  addRecipe: TypedContractMethod<
    [
      itemIds: BigNumberish[],
      amounts: BigNumberish[],
      graceCost: BigNumberish,
      rarity: BigNumberish,
      power: BigNumberish,
      uri: string,
      successRateBp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  craft: TypedContractMethod<[recipeId: BigNumberish], [void], "nonpayable">;

  daoTreasury: TypedContractMethod<[], [string], "view">;

  devWallet: TypedContractMethod<[], [string], "view">;

  graceToken: TypedContractMethod<[], [string], "view">;

  holyRelics: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recipeCount: TypedContractMethod<[], [bigint], "view">;

  recipes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        graceCost: bigint;
        resultRarity: bigint;
        resultPower: bigint;
        resultUri: string;
        successRateBp: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sacredItems: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAO_SHARE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addRecipe"
  ): TypedContractMethod<
    [
      itemIds: BigNumberish[],
      amounts: BigNumberish[],
      graceCost: BigNumberish,
      rarity: BigNumberish,
      power: BigNumberish,
      uri: string,
      successRateBp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "craft"
  ): TypedContractMethod<[recipeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "daoTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "devWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "graceToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "holyRelics"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recipeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        graceCost: bigint;
        resultRarity: bigint;
        resultPower: bigint;
        resultUri: string;
        successRateBp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sacredItems"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Crafted"
  ): TypedContractEvent<
    CraftedEvent.InputTuple,
    CraftedEvent.OutputTuple,
    CraftedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDistributed"
  ): TypedContractEvent<
    FundsDistributedEvent.InputTuple,
    FundsDistributedEvent.OutputTuple,
    FundsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "Crafted(address,uint256,uint256,bool)": TypedContractEvent<
      CraftedEvent.InputTuple,
      CraftedEvent.OutputTuple,
      CraftedEvent.OutputObject
    >;
    Crafted: TypedContractEvent<
      CraftedEvent.InputTuple,
      CraftedEvent.OutputTuple,
      CraftedEvent.OutputObject
    >;

    "FundsDistributed(uint256,uint256,uint256)": TypedContractEvent<
      FundsDistributedEvent.InputTuple,
      FundsDistributedEvent.OutputTuple,
      FundsDistributedEvent.OutputObject
    >;
    FundsDistributed: TypedContractEvent<
      FundsDistributedEvent.InputTuple,
      FundsDistributedEvent.OutputTuple,
      FundsDistributedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
